#!/bin/bash
#
CONTAINER="[chop.flywheel.io/fsl-slicer]"
echo -e "$CONTAINER  Initiated"

###############################################################################
# Built to flywheel-v0 spec.

FLYWHEEL_BASE=/flywheel/v0
OUTPUT_DIR=$FLYWHEEL_BASE/output
INPUT_DIR=$FLYWHEEL_BASE/input/input
MANIFEST=$FLYWHEEL_BASE/manifest.json
CONFIG_FILE=$FLYWHEEL_BASE/config.json

###############################################################################
# Configure the ENV
export USER=Flywheel

###############################################################################
# Initialize config parameters
mid_slices=' '

# Generate flags from the manifest
mid_slices_flag=$(jq -r <$MANIFEST '''.config.mid_slices.id')

# Parse config options from CONFIG file or MANIFEST
if [[ -f $CONFIG_FILE ]]; then
  echo "$CONTAINER  $CONFIG_FILE found. Loading config..."

  if [[ $(jq -r <$CONFIG_FILE '''.config.mid_slices') == 'true' ]]; then
    run_mid_slices=1
  fi

else
  echo "$CONTAINER  $CONFIG_FILE not found. Loading defaults from $MANIFEST..."

  if [[ $(jq -r <$MANIFEST '''.config.mid_slices.default') == 'true' ]]; then
    run_mid_slices=1
  fi

fi

###############################################################################
# Execute the main processes
input_file=$(find $INPUT_DIR/* -maxdepth 0 -type f -name "*.nii*")
echo "$CONTAINER  Input file: $input_file"
if [[ -f $input_file ]]; then
  
  # input_file_despaced=$(echo -e "${input_file}" | tr -d '[:space:]')
  # if [ $input_file != $input_file_despaced ] ; then
  #   input_file=$input_file_despaced
  #   mv "${input_file}" "${input_file_despaced}"
  # fi
  output_file_base=$(basename "$input_file" .nii.gz)
  output_file_path=${OUTPUT_DIR}/${output_file_base}_sliced.png
  echo "$CONTAINER  Ouput file: $output_file_path"

  ################# MAIN PROCESS #################
  if [[ $run_mid_slices -eq 1 ]]; then
    echo "$CONTAINER  Running with mid-slices-flag=True"
    slicer "$input_file" "$mid_slices_flag" "$output_file_path"
    
  else
    echo "$CONTAINER  Running default slicer command"
    ./slice_nifti.sh "$input_file" "$output_file_path"
  fi

################# Finish up #################
STATUS=$?
else
  echo "$CONTAINER  No valid input file!"
  exit 1
fi

# Check exit status
if [[ $STATUS == 0 ]]; then
    echo -e "$CONTAINER  Done!"

  else
    echo "$CONTAINER  command returned a non-zero exit code = [$STATUS]."
    exit 1
fi

exit 0
